name: portfolio2025
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.9
  google_fonts: ^6.1.0
  animate_do: ^3.1.2
  url_launcher: ^6.2.2
  flutter_staggered_animations: ^1.1.1
  floating_animation: ^1.0.9
  lottie: ^2.7.0
  scroll_to_index: ^3.0.1
  firebase_core: ^3.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/